### PR TITLE
fix the version problem, el use 0.0.18 but the nrepl with wrong version.

### PR DESCRIPTION
**Pull request by zheh12**
The 0.0.18 has problem el and nrepl have different version. It will break the color feature. So fix it.

### CODE REVIEW

**Comment by bbatsov** [comment]
Do you mean you get some warning because the versions are different?

**Comment by zheh12** [comment]
> Do you mean you get some warning because the versions are different?

Not the warning. The 0.0.18 el is not compatible with the 0.0.17 repl. It will break the color feature for the sayid buffer.  Most because the commit https://github.com/clojure-emacs/sayid/commit/4d03803e7cd4638ff401aeaed5aabb600e26520d.

**Comment by bbatsov** [comment]
Hmm, even if we bump those versions we already cut `sayid` 0.0.18, so I guess we'll need to bump the version again.

**Comment by bbatsov** [comment]
On a more general note - instead of hardcoding the version we should extract it from the project.clj, as we do in `cider-nrepl` (e..g. https://github.com/clojure-emacs/cider-nrepl/blob/master/src/cider_nrepl/plugin.clj#L60)  It's pretty easy to forget to update a version in several places, which caused the current issue.

**Pull request merged**
